export const tagTypes = {
  USER_INFO: "USER_INFO",
  USERS: "USERS",
  CART: "CART",
  PROVIDERS: "PROVIDERS",
  PROVIDER_PAYMENT_SETTINGS: "PROVIDER_PAYMENT_SETTINGS",
  PRODUCTS: "PRODUCTS",
  PRODUCT: "PRODUCT",
  DELIVERY_ZONES: "DELIVERY_ZONES",
  ADMINS: "ADMINS",
  SYSTEM_SETTINGS: "SYSTEM_SETTINGS",
};

export const tagTypesList = Object.values(tagTypes);
