export const tagTypes = {
  USER_INFO: "USER_INFO",
  USERS: "USERS",
  CART: "CART",
  PROVIDERS: "PROVIDERS",
  PROVIDER_PAYMENT_SETTINGS: "PROVIDER_PAYMENT_SETTINGS",
  WALLET: "WALLET",
  INVENTORY: "INVENTORY",
  PRODUCTS: "PRODUCTS",
  PRODUCT: "PRODUCT",
  RECEIPTS: "RECEIPTS",
  POS_SALES: "POS_SALES",
  MANUAL_FINANCE: "MANUAL_FINANCE",
  DELIVERY_ZONES: "DELIVERY_ZONES",
  CATEGORIES: "CATEGORIES",
  ADMINS: "ADMINS",
  SYSTEM_SETTINGS: "SYSTEM_SETTINGS",
  HOME_PAGE_CMS: "HOME_PAGE_CMS",
  AUDIT_LOGS: "AUDIT_LOGS",
  REVIEWS: "REVIEWS",
};

export const tagTypesList = Object.values(tagTypes);
