export const tagTypes = {
  USER_INFO: "USER_INFO",
  USERS: "USERS",
  CART: "CART",
  PROVIDERS: "PROVIDERS",
  PROVIDER_PAYMENT_SETTINGS: "PROVIDER_PAYMENT_SETTINGS",
  WALLET: "WALLET",
  PRODUCTS: "PRODUCTS",
  PRODUCT: "PRODUCT",
  RECEIPTS: "RECEIPTS",
  POS_SALES: "POS_SALES",
  DELIVERY_ZONES: "DELIVERY_ZONES",
  ADMINS: "ADMINS",
  SYSTEM_SETTINGS: "SYSTEM_SETTINGS",
  AUDIT_LOGS: "AUDIT_LOGS",
};

export const tagTypesList = Object.values(tagTypes);
